// bryntum/gantt/examples/react/javascript/timeranges/src/components/Gantt.js
/**
 *- Gantt functional component
 */
import React, {forwardRef} from 'react';
import { BryntumGantt } from 'bryntum-react-shared';
import { ProjectModel } from 'bryntum-gantt';

// we use forwardRef to pass ref to Gantt up to the parent
const Gantt = forwardRef((props, ref) => {

    // create and load the project
    const project = new ProjectModel({
        autoLoad : true,
        transport : {
            load : {
                url : 'data/timeranges.json'
            }
        }
    });

    return (
        <BryntumGantt 
            flex    = "1 1 auto"
            ref     = {ref}
            project = {project}
            columns = {[{ 
                type  : 'name',
                field : 'name',
                width : 250
            }]}
            timeRangesFeature = {{
                enableResizing      : true,
                showCurrentTimeLine : false,
                showHeaderElements  : true
            }}
        />
    ); // eo return
});

export default Gantt;

// eof

// bryntum/gantt/examples/vue/javascript/timeranges/src/components/Gantt.vue
<!--
 *- Gantt component
 -->
<template>
    <bryntum-gantt
        container          = "content"
        ref                = "gantt"
        :flex              = "flex"
        :project           = "project"
        :columns           = "columns"
        :timeRangesFeature = "timeRangesFeature"
    />
</template>

<script>
    import BryntumGantt from 'bryntum-vue-shared/src/BryntumGantt.vue';
    import { ProjectModel } from 'bryntum-gantt';
    import { eventBus } from '../main.js';


    export default {
        name : 'app-gantt',

        components : {
            BryntumGantt
        },

        created() {
            eventBus.$on('onShowHeadersClick', this.handleShowHeaders)
        },

        data() {
            return {
                project: new ProjectModel({
                    autoLoad : true,
                    transport : {
                        load : {
                            url : 'data/timeranges.json'
                        }
                    }
                }),
                flex : '2 1 auto',
                columns : [
                    { type : 'name', field : 'name', width : 250 }
                ],
                timeRangesFeature : {
                    enableResizing      : true,
                    showCurrentTimeLine : false,
                    showHeaderElements  : true
                }
            } // eo return from data
        }, // eo data

        methods : {
            handleShowHeaders({source}) {
                this.$refs.gantt.ganttInstance.features.timeRanges.disabled = !source.pressed;
            }
        }
    }
</script>

<!-- eof -->
