// bryntum/gantt/examples/vue/javascript/_shared/src/BryntumGantt.vue
<!--
Bryntum Gantt wrapper
-->

<template>
    <div class = "b-gantt-container"></div>
</template>

<script>
    import { Gantt } from 'bryntum-gantt';

    // Defines a Vue component that wraps Bryntum Gantt
    export default {

        name : 'gantt',

        props : {
            // Configs
            barMargin                : { default : 10, type : Number },
            calendars                : Array,
            cls                      : String,

            // The defaults for Booleans have to be specified, otherwise they would be false.
            // Setting it to undefined allows the underlying Gantt to apply its own default.
            columnLines              : {type : Boolean, default : undefined },

            columns                  : Array,
            container                : String,
            data                     : Object,
            durationDisplayPrecision : { type : [Number, Boolean], default : undefined },
            emptyText                : String,
            endDate                  : [String, Date],
            eventColor               : String,
            eventStyle               : String,
            fillLastColumn           : { type : Boolean, default : undefined },
            ganttId                  : String,
            height                   : [Number, String],
            minWidth                 : [Number, String],
            minHeight                : [Number, String],
            project                  : Object,
            readOnly                 : { type : Boolean, default : undefined },
            rowHeight                : [Number, String],
            snap                     : { type : Boolean, default : undefined },
            startDate                : [String, Date],
            subGridConfigs           : Object,
            displayDateFormat        : String,
            flex                     : String,
            listeners                : Object,
            maxHeight                : [Number, String],
            maxWidth                 : [Number, String],
            maxZoomLevel             : Number,
            minZoomLevel             : Number,
            partner                  : [Object, String],
            resourceTimeRanges       : Array,
            taskRenderer             : Function,
            scrollLeft               : Number,
            scrollTop                : Number,
            selectedEvents           : Array,
            tickWidth                : Number,
            timeResolution           : Object,
            viewportCenterDate       : Date,
            viewPreset               : [Object, String],
            width                    : [Number, String],
            zoomLevel                : Number,

            // Stores
            assignmentStore : Object,
            dependencyStore : Object,
            eventStore      : Object,
            taskStore       : Object,
            resourceStore   : Object,

            crudManager : Object,

            // Data
            assignments  : Array,
            dependencies : Array,
            events       : Array,
            tasks        : Array,
            resources    : Array,
            timeRanges   : Array,

            config : Object,

            // Features, only used for initialization
            cellEditFeature           : { type : [Boolean, Object], default : undefined },
            cellTooltipFeature        : { type : [Boolean, Object], default : undefined },
            columnDragToolbarFeature  : { type : [Boolean, Object], default : undefined },
            columnPickerFeature       : { type : [Boolean, Object], default : undefined },
            columnReorderFeature      : { type : [Boolean, Object], default : undefined },
            columnResizeFeature       : { type : [Boolean, Object], default : undefined },
            contextMenuFeature        : { type : [Boolean, Object], default : undefined },
            filterBarFeature          : { type : [Boolean, Object], default : undefined },
            filterFeature             : { type : [Boolean, Object], default : undefined },
            groupFeature              : { type : [Boolean, Object, String], default : undefined },
            groupSummaryFeature       : { type : [Boolean, Object], default : undefined },
            headerContextMenuFeature  : { type : [Boolean, Object], default : undefined },
            headerZoomFeature         : { type : Boolean, default : undefined },
            labelsFeature             : { type : [Boolean, Object], default : undefined },
            nonWorkingTimeFeature     : { type : [Boolean, Object], default : undefined },
            panFeature                : { type : [Boolean, Object], default : undefined },
            pdfExportFeature          : { type : [Boolean, Object], default : undefined },
            percentBarFeature         : { type : [Boolean, Object], default : undefined },
            projectLinesBarFeature    : { type : [Boolean, Object], default : undefined },
            quickFindFeature          : { type : [Boolean, Object], default : undefined },
            recurringTimeSpansFeature : { type : [Boolean, Object], default : undefined },
            regionResizeFeature       : { type : Boolean, default : undefined },
            resourceTimeRangesFeature : { type : [Boolean, Object], default : undefined },
            rollupsFeature            : { type : [Boolean, Object], default : undefined },
            rowReorderFeature         : { type : Boolean, default : undefined },
            searchFeature             : { type : [Boolean, Object], default : undefined },
            sortFeature               : { type : [Boolean, Object, String, Array], default : undefined },
            stripeFeature             : { type : Boolean, default : undefined },
            summaryFeature            : { type : [Boolean, Object], default : undefined },
            taskContextMenuFeature    : { type : [Boolean, Object], default : undefined },
            taskDragFeature           : { type : [Boolean, Object], default : undefined },
            taskDragCreateFeature     : { type : [Boolean, Object], default : undefined },
            taskEditFeature           : { type : [Boolean, Object], default : undefined },
            taskResizeFeature         : { type : [Boolean, Object], default : undefined },
            taskTooltipFeature        : { type : [Boolean, Object], default : undefined },
            timeRangesFeature         : { type : [Boolean, Object], default : undefined },
            treeFeature               : { type : [Boolean, Object], default : undefined }
        }, // eo props

        computed : {
            /**
             * @deprecated in favor of ganttInstance
             */
            ganttEngine() {
                console.warn('ganttEngine is deprecated. Use ganttInstance instead.')
                return this.ganttInstance;
            }
        },

        // runs after the component is attached to DOM (mounted)
        mounted() {
            const propKeys = Object.keys(this.$props);

            const config = {

                // Listeners, will relay events using $emit
                listeners : {
                    catchAll(event) {
                        // Uncomment this line to log events being emitted to console
                        //console.log(event.type);
                        this.$emit(event.type, event);
                    },

                    thisObj : this
                },

                features : {}
            };

            // Apply all props to gantt config
            propKeys.forEach(prop => {
                let match;
                if ((match = prop.match(/(.*)Feature/)) && this[prop] !== undefined) {
                    // Prop which ends with Feature is a feature config
                    config.features[match[1]] = this[prop];
                }
                else if (prop === 'config') {
                    // Prop is a config object
                    Object.assign(config, this[prop]);
                }
                else {
                    // Prop is a config
                    if (this[prop] !== undefined) {
                        config[prop] = this[prop]
                    };

                    // Set up a watcher
                    this.$watch(prop, newValue => {
                        this.ganttInstance[prop] = Array.isArray(newValue) ? newValue.slice() : newValue;
                    });
                }
            }, this);

            // console.log('config=', config, 'props=', this.$props);

            // either append Gantt to the passed container or adopt our own element
            if(this.container) {
                config.appendTo = this.container;
            }
            else {
                config.adopt = this.$el;
            }

            // Create a Bryntum Gantt with props as configs
            const engine = this.ganttInstance = new Gantt(config);

            // remove the own element if it is not needed
            if(this.container) {
                this.$el.parentNode.removeChild(this.$el);
                this.$el = engine.element;
            }

        }, // eo function mounted

        // cleanup before destroy
        beforeDestroy() {
            // Make sure Bryntum Grid is destroyed when vue component is
            this.ganttInstance.destroy();
        } // eo function beforeDestroy

    }; // eo gantt export

</script>

<!-- eof -->

// bryntum/gantt/examples/react/_shared/src/lib/BryntumGantt.js
/**
 *- Gantt React wrapper
 */
import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import { Gantt, ObjectHelper, Widget } from 'bryntum-gantt';

// Defines a React component that wraps Bryntum Gantt
class BryntumGantt extends Component {

    /**
     * @deprecated in favor of ganttInstance
     */
    get ganttEngine() {
      console.warn('ganttEngine is deprecated. Use ganttInstance instead.')
      return this.ganttInstance;
    }

    // defaults for gantt. Feel free to adjust it
    static defaultProps = {
    };

    featureRe = /Feature$/;

    /* #region Features */
    features = [
        'baselinesFeature',
        'cellEditFeature',
        'cellTooltipFeature',
        'columnDragToolbarFeature',
        'columnLinesFeature',
        'columnPickerFeature',
        'columnReorderFeature',
        'columnResizeFeature',
        'criticalPathsFeature',
        'contextMenuFeature',
        'dependenciesFeature',
        'dependencyEditFeature',
        'eventContextMenuFeature',
        'eventDragCreateFeature',
        'eventDragFeature',
        'eventEditFeature',
        'eventFilterFeature',
        'eventResizeFeature',
        'eventTooltipFeature',
        'filterBarFeature',
        'filterFeature',
        'groupFeature',
        'groupSummaryFeature',
        'headerContextMenuFeature',
        'labelsFeature',
        'nonWorkingTimeFeature',
        'panFeature',
        'pdfExportFeature',
        'percentBarFeature',
        'progressLineFeature',
        'projectLinesFeature',
        'quickFindFeature',
        'recurringTimeSpansFeature',
        'regionResizeFeature',
        'resourceTimeRangesFeature',
        'rollupsFeature',
        'rowReorderFeature',
        'scheduleContextMenuFeature',
        'scheduleTooltipFeature',
        'searchFeature',
        'sortFeature',
        'stripeFeature',
        'summaryFeature',
        'taskContextMenuFeature',
        'taskDragCreateFeature',
        'taskDragFeature',
        'taskEditFeature',
        'taskResizeFeature',
        'taskTooltipFeature',
        'timeRangesFeature',
        'treeFeature'
    ];
    /* #endregion */

    /* #region Configs */
    configs = [
        'animateRemovingRows',
        'barMargin',
        'cls',
        'columnLines',
        'columns',
        'data',
        'dataset',
        'disabled',
        'displayDateFormat',
        'durationDisplayPrecision',
        'emptyText',
        'enableDeleteKey',
        'enableTextSelection',
        'endDate',
        'eventColor',
        'eventStyle',
        'fillLastColumn',
        'flex',
        'forceFit',
        'fullRowRefresh',
        'height',
        'hideHeaders',
        'listeners',
        'loadMask',
        'longPressTime',
        'managedEventSizing',
        'maxHeight',
        'maxWidth',
        'maxZoomLevel',
        'milestoneLayoutMode',
        'minHeight',
        'minWidth',
        'minZoomLevel',
        'navigator',
        'partner',
        'plugins',
        'project',
        'readOnly',
        'ref',
        'responsiveLevels',
        'ripple',
        'rowHeight',
        'scrollLeft',
        'scrollTop',
        'selectedCell',
        'selectedRecord',
        'selectedRecords',
        'showDirty',
        'showRemoveRowInContextMenu',
        'snap',
        'snapRelativeToEventStartDate',
        'startDate',
        'store',
        'style',
        'subGridConfigs',
        'taskRenderer',
        'tickWidth',
        'timeAxis',
        'timeResolution',
        'title',
        'tooltip',
        'viewportCenterDate',
        'viewPreset',
        'width',
        'workingTime',
        'zoomLevel',
        'zoomLevels'
    ];
    /* #endregion */

    state = {
        portals    : new Set(),
        generation : 0
    };

    releaseReactCell(cellElement) {
        const
            {state} = this,
            cellElementData = cellElement._domData;

        // Cell already has a react component in it, remove
        if (cellElementData.reactPortal) {
            state.portals.delete(cellElementData.reactPortal);

            this.setState({
                portals    : state.portals,
                generation : state.generation + 1
            });

            cellElementData.reactPortal = null;
        }
    }

    // React component rendered to DOM, render gantt to it
    componentDidMount() {
        const
            config = {
                adopt           : this.el,
                callOnFunctions : true,
                features        : {},

                // Hook called by engine when requesting a cell editor
                processCellEditor : ({editor, field}) => {
                    // String etc handled by feature, only care about fns returning React components here
                    if (typeof editor !== 'function') {
                        return;
                    }

                    // Wrap React editor in an empty widget, to match expectations from CellEdit/Editor and make alignment
                    // etc. work out of the box
                    const wrapperWidget = new Widget({
                        name : field // For editor to be hooked up to field correctly
                    });

                    // Ref for accessing the React editor later
                    wrapperWidget.reactRef = React.createRef();

                    // column.editor is expected to be a function returning a React component (can be JSX). Function is
                    // called with the ref from above, it has to be used as the ref for the editor to wire things up
                    const reactComponent = editor(wrapperWidget.reactRef);
                    if (reactComponent.$$typeof !== Symbol.for('react.element')) {
                        throw new Error('Expect a React element');
                    }

                    let editorValidityChecked = false;

                    // Add getter/setter for value on the wrapper, relaying to getValue()/setValue() on the React editor
                    Object.defineProperty(wrapperWidget, 'value', {
                        enumerable : true,
                        get        : function() {
                            return wrapperWidget.reactRef.current.getValue();
                        },
                        set        : function(value) {
                            const component = wrapperWidget.reactRef.current;

                            if (!editorValidityChecked) {
                                const misses = ['setValue', 'getValue', 'isValid', 'focus'].filter(fn => !(fn in component));

                                if (misses.length) {
                                    throw new Error(`
                                        Missing function${misses.length > 1 ? 's' : ''} ${misses.join(', ')} in ${component.constructor.name}.
                                        Cell editors must implement setValue, getValue, isValid and focus
                                    `);
                                }

                                editorValidityChecked = true;
                            }

                            const context = wrapperWidget.owner.cellEditorContext;
                            component.setValue(value, context);
                        }
                    });

                    // Add getter for isValid to the wrapper, mapping to isValid() on the React editor
                    Object.defineProperty(wrapperWidget, 'isValid', {
                        enumerable : true,
                        get        : function() {
                            return wrapperWidget.reactRef.current.isValid();
                        }
                    });

                    // Override widgets focus handling, relaying it to focus() on the React editor
                    wrapperWidget.focus = () => {
                        wrapperWidget.reactRef.current.focus && wrapperWidget.reactRef.current.focus();
                    };

                    // Create a portal, making the React editor belong to the React tree although displayed in a Widget
                    const portal = ReactDOM.createPortal(reactComponent, wrapperWidget.element);
                    wrapperWidget.reactPortal = portal;

                    const {state} = this;
                    // Store portal in state to let React keep track of it (inserted into the Grid component)
                    state.portals.add(portal);
                    this.setState({
                        portals    : state.portals,
                        generation : state.generation + 1
                    });

                    return {editor : wrapperWidget};
                },

                // Hook called by engine when rendering cells, creates portals for JSX supplied by renderers
                processCellContent : ({cellContent, cellElement, cellElementData, record}) => {
                    let shouldSetContent = cellContent != null;

                    // Release any existing React component
                    this.releaseReactCell(cellElement);

                    // Detect React component
                    if (cellContent && cellContent.$$typeof === Symbol.for('react.element')) {
                        // Excluding special rows for now to keep renderers simpler
                        if (!record.meta.specialRow) {
                            // Clear any non-react content
                            const firstChild = cellElement.firstChild;
                            if (!cellElementData.reactPortal && firstChild) {
                                firstChild.data = '';
                            }

                            // Create a portal, belonging to the existing React tree but render in a cell
                            const portal = ReactDOM.createPortal(cellContent, cellElement);
                            cellElementData.reactPortal = portal;

                            const {state} = this;
                            // Store in state for React to not loose track of the portals
                            state.portals.add(portal);
                            this.setState({
                                portals    : state.portals,
                                generation : state.generation + 1
                            });
                        }
                        shouldSetContent = false;
                    }

                    return shouldSetContent;
                }
            };

        // relay properties with names matching this.featureRe to features
        this.features.forEach(featureName => {
            if (featureName in this.props) {
                config.features[featureName.replace(this.featureRe, '')] = this.props[featureName];
            }
        });

        // Handle config (relaying all props except those used for features to gantt)
        Object.keys(this.props).forEach(propName => {
            if (!propName.match(this.featureRe) && undefined !== this.props[propName]) {
                if (propName === 'features') {
                    console.warn('Passing "features" object as prop is not supported. Set features one-by-one with "Feature" suffix, for example "timeRangesFeature".');
                }
                else {
                    config[propName] = this.props[propName];
                }
            }
        });

        // console.log(config);

        // Create the actual gantt, used as engine for the wrapper
        const engine = this.ganttInstance = this.props.ganttClass ? new this.props.ganttClass(config) : new Gantt(config);

        // Release any contained React components when a row is removed
        engine.rowManager.on({
            removeRow : ({ row }) => row.cells.forEach(cell => this.releaseReactCell(cell))
        });

        // Map all features from ganttInstance to gantt to simplify calls
        Object.keys(engine.features).forEach(key => {
            let featureName = key + 'Feature';
            if (!this[featureName]) {
                this[featureName] = engine.features[key];
            }
        });
    }

    // React component removed, destroy engine
    componentWillUnmount() {
        this.ganttInstance.destroy();
    }

    // Component about to be updated, from changing a prop using state. React to it depending on what changed and
    // prevent react from re-rendering our component.
    shouldComponentUpdate(nextProps, nextState) {
        const
            { props, ganttInstance : engine } = this,
            // These props are ignored or has special handling below
            excludeProps = [
                'adapter',
                'children',
                'columns',
                'events',
                'eventsVersion',
                'features', // #445 React: Scheduler crashes when features object passed as prop
                'listeners', // #9114 prevents the crash when listeners are changed at runtime
                'ref',
                'resources',
                'resourcesVersion',
                'timeRanges',
                ...this.features
            ];

        // Reflect configuration changes. Since most gantt configs are reactive the gantt will update automatically
        Object.keys(props).forEach(propName => {
            // Only apply if prop has changed
            if (!excludeProps.includes(propName) && !ObjectHelper.isEqual(props[propName], nextProps[propName])) {
                engine[propName] = nextProps[propName];
            }
        });

        // xxVersion used to flag that data has changed
        if (nextProps.resourcesVersion !== props.resourcesVersion) {
            engine.resources = nextProps.resources;
        }

        if (nextProps.eventsVersion !== props.eventsVersion) {
            engine.eventStore.data = nextProps.events;
        }

        // Reflect feature config changes
        this.features.forEach(featureName => {
            const currentProp = props[featureName],
                nextProp = nextProps[featureName];

            if (featureName in props && !ObjectHelper.isEqual(currentProp, nextProp)) {
                engine.features[featureName.replace(this.featureRe, '')].setConfig(nextProp);
            }
        });

        // Reflect JSX cell changes
        return (nextState.generation !== this.state.generation);
    }

    render() {
        return <div ref={el => this.el = el}>{this.state.portals}</div>;
    } // eo function render

} // eo class BryntumGantt

export default BryntumGantt;

// eof
