// bryntum/gantt/examples/vue/javascript/pdf-export/src/components/Header.vue
<!--
/**
 * Header with title and buttons
 */
-->

<template>
    <header class="app-header">
        <h1><a :href="link">{{ $props.title }}</a></h1>
        <app-button color="b-skip-test b-orange b-raised" text="Export to PDF/PNG" action="export"></app-button>
        <fullscreen-button></fullscreen-button>
    </header>
</template>

<script>
    import FullscreenButton from 'bryntum-vue-shared/src/FullscreenButton.vue';
    import AppButton from './Button.vue';

    export default {
        name  : 'app-header',
        props : {
            link  : { type : String, default : '..' },
            title : { type : String, default : 'Example Header' }
        },
        components: {
            FullscreenButton,
            AppButton
        },
        mounted() {
            document.title = this.$props.title;
        }
    } // exports the header components
</script>

<style>
    .app-header {
        padding             : 2.1em .5em 2.1em 5em;
        background          : url(~bryntum-resources/images/logo_bryntum_bw.png) #2667c8;
        background-repeat   : no-repeat;
        background-size     : 40px;
        background-position : center left 1.5em;
        display             : flex;
    }

    .app-header h1 {
        margin      : 0;
        font-size   : 1.8em;
        color       : #fff;
        font-weight : normal;
        flex        : 1;
        align-self  : center;
    }

    .app-header a {
        color           : inherit;
        text-decoration : none;
    }

    .app-header button {
        margin-right  : 1em;
    }

</style>

<!-- eof -->

// bryntum/gantt/examples/react/javascript/pdf-export/src/components/Header.js
/**
 * Page header component. Contains also controls (tools)
 */

// libraries
import React from 'react';

// our stuff
import { BryntumWidget, FullscreenButton, Tools } from 'bryntum-react-shared';

const header = props => {
    const
        title = props.title || document.title || '',
        href = props.titleHref || '#';

    return (
        <header className="demo-header">
            <div id="title-container">
                <a id="title" href={href}>{title}</a>
            </div>
            <Tools>
                <BryntumWidget
                    type        = "button"
                    text        = "Export to PDF/PNG"
                    cls         = "b-orange b-raised b-skip-test"
                    // eslint-disable-next-line
                    style       = "margin-right: 1em"
                    listeners   = {{ click : props.onExportClick }}
                    container   = "tools"
                ></BryntumWidget>
                <FullscreenButton container='tools'/>
            </Tools>
        </header>
    );

}; // eo function header

export default header;

// eof
